### ISSUE TITLE
 Presented multi-factor authentication has expired due to policies configured by your administrator

### ISSUE THREAD

**Issue by capri02** [Azure/api-management-developer-portal#1310]
## Describe the bug
I am getting a MFA error when I run the capture.js script which calls the command mentioned below.

**Command Name**
`az account get-access-token`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '797f4846-ba00-4fd7-XXXXXXXXXXXXXXX'.\r\nTrace ID: 66ceeed6-c158-4dcc-b4ed-b139f06a1600\r\nCorrelation ID: c5433cf4-3e78-4934-8706-da69c15ee849\r\nTimestamp: 2021-05-18 13:45:56Z","error_codes":[50078],"timestamp":"2021-05-18 13:45:56Z","trace_id":"66ceeed6-c158-4dcc-b4ed-b139f06a1600","correlation_id":"c5433cf4-3e78-4934-8706-da69c15ee849","suberror":"basic_action"}
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli\azure\cli\command_modules\profile\custom.py", line 75, in get_access_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\_profile.py", line 635, in get_raw_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\_profile.py", line 964, in retrieve_token_for_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\authentication_context.py", line 145, in acquire_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\authentication_context.py", line 128, in _acquire_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\authentication_context.py", line 143, in token_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\token_request.py", line 347, in get_token_from_cache_with_refresh
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\token_request.py", line 127, in _find_token_from_cache
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\cache_driver.py", line 199, in find
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\cache_driver.py", line 177, in _refresh_entry_if_necessary
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\cache_driver.py", line 153, in _refresh_expired_entry
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\token_request.py", line 137, in _get_token_with_token_response
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\token_request.py", line 339, in _get_token_with_refresh_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\token_request.py", line 112, in _oauth_get_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\adal\adal\oauth2_client.py", line 289, in get_token
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '797f4846-ba00-XXXXXXXXXXXXX'.\r\nTrace ID: 66ceeed6-c158-4dcc-b4ed-b139f06a1600\r\nCorrelation ID: c5433cf4-3e78-4934-8706-da69c15ee849\r\nTimestamp: 2021-05-18 13:45:56Z","error_codes":[50078],"timestamp":"2021-05-18 13:45:56Z","trace_id":"66ceeed6-c158-4dcc-b4ed-b139f06a1600","correlation_id":"c5433cf4-3e78-4934-8706-da69c15ee849","suberror":"basic_action"}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource-type {} --output {} --query {}`

## Expected Behavior
The command should get the SAS token without any problem and get the content from an APIM instance.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0

Extensions:
azure-devops 0.18.0

```

**Comment by capri02** [comment]
Closing it, Since it can be fixed by the organization and has nothing to do with the APIM scripts.
