### ISSUE TITLE
"Error: Cannot find module 'azure-storage'" message received when running the migration scripts

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#418]
When running the "migrate.bat" script from the released version 2.3.1, I receive the following error after the cleanup.js has been invoked: Error: Cannot find module 'azure-storage'
(I have already installed node.js, npm packages and I have already installed the azure-storage package: `npm install azure-storage`). Has anyone an idea what the issue could be?
Here some more details from the log text:

Error: Cannot find module 'azure-storage'
Require stack:
- c:\Temp\api-management-developer-portal-2.1.3\cleanup.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (c:\Temp\api-management-developer-portal-2.1.3\cleanup.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'c:\\Temp\\api-management-developer-portal-2.1.3\\cleanup.js' ]

Also an earlier version of the script that already worked does not work anymore. So I assume, I need to get the latest sripts up and running before I am able to continue relying on the new portal for the API documentation.

**Comment by AnRei123** [comment]
This issue has been solved. I am very new to all this topics. I found out that the npm package needs to be installed in the same folder where the package.json file is.

**Comment by SahinOzdemir** [comment]
@AnRei123 can you then close the issue?
