### ISSUE TITLE
'npm run publish' failing with 'Could not search object pages' error, while publishing the code locally

### ISSUE THREAD

**Issue by jerryanto** [Azure/api-management-developer-portal#432]
After configuring and doing the config changes, I tried to publish it locally using the command 'npm run publish' which got failed with the below error.

Publishing website...
Error: Could not search object 'pages'. Error: Unable to complete request. Error: Could not complete the request. Please try again later.
    at MapiObjectStorage.<anonymous> (D:\Catalyst\Catalyst-Dev-Portal\dist\publisher\index.js:167459:23)
    at Generator.throw (<anonymous>)
    at rejected (D:\Catalyst\Catalyst-Dev-Portal\dist\publisher\index.js:167183:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Could not search object 'uploads'. Error: Unable to complete request. Error: Could not complete the request. Please try again later.
    at MapiObjectStorage.<anonymous> (D:\Catalyst\Catalyst-Dev-Portal\dist\publisher\index.js:167459:23)
    at Generator.throw (<anonymous>)
    at rejected (D:\Catalyst\Catalyst-Dev-Portal\dist\publisher\index.js:167183:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I followed the procedure mentioned in the link below
https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal

Kindly help

**Comment by azaslonov** [comment]
Hi @jerryanto,

Please check that you have specified the correct settings in `config.publish.json` file. If still can't figure this out, please send your service name to apimportalfeedback@microsoft.com and we'll help you to make the right config.

**Comment by azaslonov** [comment]
I'm closing this issue since we're taking it offline.

**Comment by srimarru** [comment]
I am having the same issue. I have generated a new SAS token and updated config.design.josn and config.publish.json.  npm publish run is throwing the below error and not publishing the site. 

Error: Unable to complete publishing. Error: Unable to search media: Error: Could not search object 'uploads'. Error: Unauthorized request.
    at MapiObjectStorage.eval (webpack://apim-developer-portal/./src/persistence/mapiObjectStorage.ts?:378:23)
    at Generator.throw (<anonymous>)
    at rejected (webpack://apim-developer-portal/./src/persistence/mapiObjectStorage.ts?:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MediaService.eval (webpack://apim-developer-portal/./node_modules/@paperbits/common/media/mediaService.ts?:94:23)
    at Generator.throw (<anonymous>)
    at rejected (webpack://apim-developer-portal/./node_modules/@paperbits/common/media/mediaService.ts?:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SitePublisher.eval (webpack://apim-developer-portal/./node_modules/@paperbits/core/publishing/sitePublisher.ts?:40:23)
    at Generator.throw (<anonymous>)
    at rejected (webpack://apim-developer-portal/./node_modules/@paperbits/core/publishing/sitePublisher.ts?:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
