### ISSUE TITLE
Generate Script Errors

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/api-management-developer-portal#458]
**As I'm following your wiki on generating the content, I have two errors that occur.  I have triple checked my SAS, etc. and when node ./generate is called via the bat the following error occurs:**  
```
(node:11664) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.                        
(node:11664) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 23.217.138.109:443                                                                                                              
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)                                                                                                                                        
(node:11664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was
 not handled with .catch(). (rejection id: 1)                                                                                                                                                              
(node:11664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
.                 
```                                             

**After that fails, the bat continues and I receive the following for ./upload (I have reviewed my settings a ton of times):**
```
StorageError: The specified container does not exist.
RequestId:4fe58e0a-401e-0002-4f7c-dbe251000000
Time:2020-02-04T17:02:54.4509314Z
    at Function.StorageServiceClient._normalizeError (C:\src\sandbox\api-management-developer-portal\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1205:23)
    at BlobService.StorageServiceClient._processResponse (C:\src\sandbox\api-management-developer-portal\node_modules\azure-storage\lib\common\services\storageserviceclient.js:751:50)
    at Request.processResponseCallback [as _callback] (C:\src\sandbox\api-management-developer-portal\node_modules\azure-storage\lib\common\services\storageserviceclient.js:319:37)
    at Request.self.callback (C:\src\sandbox\api-management-developer-portal\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (C:\src\sandbox\api-management-developer-portal\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (C:\src\sandbox\api-management-developer-portal\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7) {
  name: 'StorageError',
  message: 'The specified container does not exist.\n' +
    'RequestId:4fe58e0a-401e-0002-4f7c-dbe251000000\n' +
    'Time:2020-02-04T17:02:54.4509314Z',
  code: 'ContainerNotFound',
  statusCode: 404,
  requestId: '4fe58e0a-401e-0002-4f7c-dbe251000000'
}                                                                                                                                             
```

**Comment by ygrik** [comment]
Hello @TravisLRiffle 
it looks like you have connectivity issue
(node:11664) UnhandledPromiseRejectionWarning: **Error: connect ECONNREFUSED 23.217.138.109:443**

Please check your config settings

**Comment by TravisLRiffle** [comment]
I've triple checked my config - is there something on APIM side I need to configure outside of what you have in the WIKI?  I'm kind of stuck at this point.

**Comment by ygrik** [comment]
@TravisLRiffle
could you please submit a support ticket with details (apim service name, config, migrate.bat files).
