### ISSUE TITLE
New Dev Potal Generate.bat error when running from a mac

### ISSUE THREAD

**Issue by guideveloper** [Azure/api-management-developer-portal#498]
When trying to self host the portal on azure and after following the wiki on step 3

https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-3-provision-the-default-template

You get an error when trying to run the generate.bat script on a mac.

The Error message I get

`innerspace@Craigs-MacBook-Pro scripts % ./generate.bat
./generate.bat: line 1: @REM: command not found
(node:79333) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '%data_file%'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at restore (/Users/innerspace/Projects/Dfe/developer-portal/scripts/generate.js:50:21)
    at Object.<anonymous> (/Users/innerspace/Projects/Dfe/developer-portal/scripts/generate.js:60:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:79333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:79333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/Users/innerspace/Projects/Dfe/developer-portal/node_modules/azure-storage/lib/common/services/servicesettings.js:83
        throw new SyntaxError(SR.INVALID_CONNECTION_STRING);
        ^

SyntaxError: Connection strings must be of the form "key1=value1;key2=value2".
    at Object.exports.parseAndValidateKeys (/Users/innerspace/Projects/Dfe/developer-portal/node_modules/azure-storage/lib/common/services/servicesettings.js:83:15)
    at Function.StorageServiceSettings.createFromConnectionString (/Users/innerspace/Projects/Dfe/developer-portal/node_modules/azure-storage/lib/common/services/storageservicesettings.js:122:43)
    at Function.StorageServiceClient.getStorageSettings (/Users/innerspace/Projects/Dfe/developer-portal/node_modules/azure-storage/lib/common/services/storageserviceclient.js:919:53)
    at new BlobService (/Users/innerspace/Projects/Dfe/developer-portal/node_modules/azure-storage/lib/services/blob/blobservice.core.js:103:53)
    at Object.exports.createBlobService (/Users/innerspace/Projects/Dfe/developer-portal/node_modules/azure-storage/lib/azure-storage.js:98:10)
    at Object.<anonymous> (/Users/innerspace/Projects/Dfe/developer-portal/scripts/upload.js:48:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
innerspace@Craigs-MacBook-Pro scripts % i ｢atl｣: Checking started in a separate process...
i ｢atl｣: Time: 1033ms`

**Comment by michaeltnguyen** [comment]
Hi, .bat files are only for windows.  If you look at the source for `generate.js`, you'll see that inputs are just passed in as command line args.  https://github.com/Azure/api-management-developer-portal/blob/master/scripts/generate.js#L3

so try something like

`node generate.js <managementEndpoint> <accessToken> <dataFile>`

**Comment by azaslonov** [comment]
Hi @guideveloper, yes, @michaeltnguyen is right, it is for Windows only, we have plans to implement proper CLI tools that would work for everybody, but for now please try out what Michael suggests.

**Comment by guideveloper** [comment]
Thanks guys, I ended up just running this and seemed to deploy the files fine...
`az storage blob upload-batch --source dist/website --destination '$web' --account-name <account-name> --account-key <account-key>`
