### ISSUE TITLE
Unable to publish locally using "npm run publish"

### ISSUE THREAD

**Issue by maheshkumagali** [Azure/api-management-developer-portal#595]
**Unable to publish locally after following all the steps mentioned in the [documentation](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal).**

## Reproduction steps

Cloned the repository and followed all the steps mentioned in the documentation but i am unable to publish locally using "npm run publish" folder. The publish is working fine in others' machines but only i have the issue in my machine.

##Expected behaviour:
Code should be published to "dist/website" folder

## Is your portal managed or self-hosted?
Self-hosted

## Release tag or commit SHA (if using self-hosted version)
10.11.12

## API Management service name
"apimdigital-dev"

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome, Edge
 - Version: Latest

## Additional context

Error:

(node:12516) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:12516) _UnhandledPromiseRejectionWarning: TypeError: invalid options argument
    at optsArg (C:\Users\MAGALI\repos\Dev portal new\api-management-developer-portal-master\dist\publisher\index.js:136663:11)
    at mkdirp (C:\Users\MAGALI\repos\Dev portal new\api-management-developer-portal-master\dist\publisher\index.js:136454:10)
    at C:\Users\MAGALI\repos\Dev portal new\api-management-developer-portal-master\dist\publisher\index.js:183119:13
    at new Promise (<anonymous>)
    at FileSystemBlobStorage.uploadBlob (C:\Users\MAGALI\repos\Dev portal new\api-management-developer-portal-master\dist\publisher\index.js:183117:16)
    at LocalStyleBuilder.<anonymous> (C:\Users\MAGALI\repos\Dev portal new\api-management-developer-portal-master\dist\publisher\index.js:37575:42)
    at Generator.next (<anonymous>)
    at C:\Users\MAGALI\repos\Dev portal new\api-management-developer-portal-master\dist\publisher\index.js:37560:71
    at new Promise (<anonymous>)
    at module.exports../node_modules/@paperbits/core/publishing/localStyleBuilder.ts.__awaiter_ (C:\Users\MAGALI\repos\Dev portal new\api-management-developer-portal-master\dist\publisher\index.js:37556:12)
(node:12516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:12516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by azaslonov** [comment]
Hi Mahesh, sorry for the late reply. Can you please send your config.publish.json (with connection strings scrambled a bit, but not totally, to be able to see what format you use) to apimportalfeedback@microsoft.com?
