### ISSUE TITLE
NPM issue doing the publish command

### ISSUE THREAD

**Issue by Gordonby** [Azure/api-management-developer-portal#788]
# Bug description

Following the guide:https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal
results in an npm error

## Reproduction steps

1. Follow the self hosting guide (i'm writing a script to make it a bit easier: https://github.com/Gordonby/api-management-developer-portal/blob/PowerShell-jumpstart-script/Init-APIM-Dev-Portal.ps1)
2. On npm run publish - wait for the error

## Expected behaviour

That the publish script generates the web assets

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

ContosoTravel

## Environment

 - Operating system: Windows 10
 - Browser: N/A
 - Version: N/A

## Additional context

  Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--4-1!node_modules/postc
ss-loader/src/index.js!node_modules/sass-loader/dist/cjs.js!src/themes/website/styles/styles.scss:
        Entrypoint mini-css-extract-plugin = *
        [0] ./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/postcss-loader/src!./no
de_modules/sass-loader/dist/cjs.js!./src/themes/website/styles/styles.scss 55.6 KiB {0} [built]
            + 1 hidden module
npm : undefined:1
At line:1 char:1
+ npm run publish
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (undefined:1:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ï¿½ï¿½{
^
SyntaxError: Unexpected token ï¿½ in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> 
(C:\ReposGitHub\apim-devportal\api-management-developer-portal\dist\publisher\index.js:113:28)
    at __webpack_require__ 
(C:\ReposGitHub\apim-devportal\api-management-developer-portal\dist\publisher\index.js:21:30)
    at Object.<anonymous> 
(C:\ReposGitHub\apim-devportal\api-management-developer-portal\dist\publisher\index.js:92:18)
    at __webpack_require__ 
(C:\ReposGitHub\apim-devportal\api-management-developer-portal\dist\publisher\index.js:21:30)
    at 
C:\ReposGitHub\apim-devportal\api-management-developer-portal\dist\publisher\index.js:85:18
    at Object.<anonymous> 
(C:\ReposGitHub\apim-devportal\api-management-developer-portal\dist\publisher\index.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
npm
 
ERR!
 
code
 ELIFECYCLE
npm
 
ERR!
 
errno 1
npm
 
ERR!
 apim-developer-portal@2.0.0 publish: `webpack --config webpack.publisher.js && node 
dist/publisher/index.js`
npm
 
ERR!
 Exit status 1
npm
 
ERR!
 
npm 
ERR!
 Failed at the apim-developer-portal@2.0.0 publish script.
npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.
npm

**Comment by Gordonby** [comment]
Revisited this, checking script output etc.

**Generate.bat**
Doesn't look like this ran properly.
![image](https://user-images.githubusercontent.com/17914476/88906436-59427b80-d24f-11ea-84cc-a531cdc49aa6.png)

Then thought i'd try the shell script out in WSL

**Generate.sh**
![image](https://user-images.githubusercontent.com/17914476/88906613-8e4ece00-d24f-11ea-9a21-47d8963ef29a.png)

Here's how the variables look
`export management_endpoint="ContosoTravel.management.azure-api.net"
export access_token="SharedAccessSignature mysastokenisprivate=="
export storage_connection_string="DefaultEndpointsProtocol=https;AccountName=contosotravel9452;AccountKey=myaccesskeyisprivate==;EndpointSuffix=core.windows.net"
export data_file="./data.json"
export media_folder="./media"`

**Comment by Gordonby** [comment]
Will raise on StackOverflow.
