### ISSUE TITLE
Error: Unable to publish when Delegation Enable

### ISSUE THREAD

**Issue by asasar** [Azure/api-management-developer-portal#830]
I am following [Self hosting the portal](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal) documentation. 

## Bug description
At enable the identity delegation and trying to publish the site with  the command 

> npm run publish

Publishing {"message":"Publishing website..."}                                                                                                                                                                                          
Publishing {"message":"Publishing page APIs: Changelog - Microsoft Azure API Management - developer portal..."}                           
Publishing {"message":"Publishing page APIs: List - Microsoft Azure API Management - developer portal..."}                                
Publishing {"message":"Publishing page Errors: 500 Internal error - Microsoft Azure API Management - developer portal..."}                
Publishing {"message":"Publishing page APIs: Details - Microsoft Azure API Management - developer portal..."}                             
Publishing {"message":"Publishing page Change password - Microsoft Azure API Management - developer portal..."}                           
Publishing {"message":"Publishing page Confirm password - Microsoft Azure API Management - developer portal..."}                          
Publishing {"message":"Publishing page Errors: 404 Page not found - Microsoft Azure API Management - developer portal..."}                
Publishing {"message":"Publishing page Sign in - Microsoft Azure API Management - developer portal..."}                                   
Publishing {"message":"Publishing page Sign up - Microsoft Azure API Management - developer portal..."}                                   
Publishing {"message":"Publishing page Products: Details - Microsoft Azure API Management - developer portal..."}                         
Publishing {"message":"Publishing page Sign up with OAuth - Microsoft Azure API Management - developer portal..."}                        
Publishing {"message":"Publishing page Products: List - Microsoft Azure API Management - developer portal..."}                            
Publishing {"message":"Publishing page Reset password - Microsoft Azure API Management - developer portal..."}                            
Publishing {"message":"Publishing page Home - Microsoft Azure API Management - developer portal..."}                                      
Error: Unable to complete publishing. Error: Unable to complete pages publishing. Error: Unable to publish page "Sign in": 
   0 t PagePublisher.<anonymous> (C:\pathToFiles\dist\publisher\index.js :44939:23)                                                                                                                                
    at Generator.throw (<anonymous>)                                                                                                      
    at rejected (C:\pathToFiles\dist\publisher\index.js:44793:65)       
    at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                   
    at PagePublisher.<anonymous> (C:\pathToFiles\dist\publisher\index.js :44974:23)                                                                                                                                
    at Generator.throw (<anonymous>)                                                                                                      
    at rejected (C:\pathToFiles\dist\publisher\index.js:44793:65)       
    at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                   
    at SitePublisher.<anonymous> (C:\pathToFiles\dist\publisher\index.js:63433:23)                                                                                                                                
    at Generator.throw (<anonymous>)                                                                                                      
    at rejected (C:\pathToFiles\dist\publisher\index.js:63399:65)       

## Reproduction steps

1. Go to Developer portal -> Delegation
2. Check Delegate sign-in & sign-up
3. Enter Delegation endpoint URL -> https://myIdentityServer4.azurewebsites.net/Account/Delegation
4. Save
5. npm run publish

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

**Comment by tOmoness** [comment]
Related to https://github.com/Azure/api-management-developer-portal/issues/785 for sure.

**Comment by ygrik** [comment]
Please add following parameter in config.publish.json
"backendUrl": "https://<service name>.developer.azure-api.net"

Close with https://github.com/Azure/api-management-developer-portal/pull/834
