### ISSUE TITLE
Error: Unable to complete publishing. Error: Unable to complete pages publishing. Error: Unable to publish page "Sign in": 0

### ISSUE THREAD

**Issue by venkateshnamb** [Azure/api-management-developer-portal#897]
**Error: Unable to complete publishing. Error: Unable to complete pages publishing. Error: Unable to publish page "Sign in": 0**

## Bug description

I have cloned the latest release 2.4.3 and tried to build and publish and getting the following error

## Expected behavior

> npm run build 

> npm run publish

Error: Unable to complete publishing. Error: Unable to complete pages publishing. Error: Unable to publish page "Sign in": 0
    at PagePublisher.<anonymous> (C:\Users\XXX\Documents\MS Dev Portal\api-management-developer-portal\dist\publisher\index.js:44939:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\XXX\Documents\MS Dev Portal\api-management-developer-portal\dist\publisher\index.js:44793:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at PagePublisher.<anonymous> (C:\Users\XXX\Documents\MS Dev Portal\api-management-developer-portal\dist\publisher\index.js:44974:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\XXX\Documents\MS Dev Portal\api-management-developer-portal\dist\publisher\index.js:44793:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at SitePublisher.<anonymous> (C:\Users\XXX\Documents\MS Dev Portal\api-management-developer-portal\dist\publisher\index.js:63433:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\XXX\Documents\MS Dev Portal\api-management-developer-portal\dist\publisher\index.js:63399:65)

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[release `2.4.3`]

## Environment

 - Operating system: Windows
 - Version: Windows 10

**Comment by mikebudzynski** [comment]
@venkateshnamb If it's related to this tutorial: https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal, I suggest that you reach out to Azure Support.

**Comment by venkateshnamb** [comment]
@mikebudzynski - Thanks for reaching our quickly, it was working fine for me with the previously version 2.42., I just cloned the 2.4.3 version and trying to build an publish, then I am getting the error mentioned, could you please recommend to steps to resolve

**Comment by mikebudzynski** [comment]
Are your tokens in the config files up-to-date?

**Comment by venkateshnamb** [comment]
Thanks it is working fine, using the old token and config files, thanks a lot for the help
