### ISSUE TITLE
migrate portal developer

### ISSUE THREAD

**Issue by CoumbaNDI** [Azure/api-management-developer-portal#995]
## Bug description

Can't manage to migrate a developer portel from an environnement to an other
## Reproduction steps

after npm install at the root of the project doing this command
node migrate --sourceEndpoint X.management.azure-api.net --destEndpoint Xclient.management.azure-api.net --publishEndpoint uat-developers.gs1.fr --destId integration --sourceId integration --destKey "SharedAccessSignature integration&202011261019&..." --sourceKey "SharedAccessSignature integration&202011261020&..."

I get this error

Error: Cannot find module X\api-management-developer-portal-master (2)\migrate'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

## Is your portal managed or self-hosted?

Managed
## Release tag or commit SHA (if using self-hosted version)

![image](https://user-images.githubusercontent.com/52564104/97332752-1c504a00-187b-11eb-874d-205c2c4a5c48.png)

**Comment by mikebudzynski** [comment]
@CoumbaNDI You need to run the script from its own folder - you can navigate there with the following command `cd scripts.v2`.

**Comment by azaslonov** [comment]
Closing due to inactivity. Please feel free to re-open shall you need further assistance.
